#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/bookmng?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
#  synchronization
#mybatis.mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 20010930
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookmng?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  aop:
    proxy-target-class: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  sql:
    init:
      mode:
      platform: mysql
cors:
  accessControlAllowOrigin: http://localhost:4200
  accessControlAllowHeaders: Content-Type
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.mybatis: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true
keys:
  list:
    - sk-P6ZRVBSxKzQb8jaRJ60oh1rChIQiQVcYcL7fLiLFjytKm06t
    - sk-P6ZRVBSxKzQb8jaRJ60oh1rChIQiQVcYcL7fLiLFjytKm06t
